import type { Metadata } from 'next';
import './globals.css';
import { roboto } from './font';
import { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
    title: 'Real Chat App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={roboto.className}>
                {children}
                <Toaster
                    position="top-center"
                    reverseOrder={true}
                    toastOptions={{
                        error: {
                            style: {
                                background: '#EF4444',
                                color: '#FFFFFF',
                            },
                            duration: 2000,
                        },
                    }}
                />
            </body>
        </html>
    );
}
